version: '3'

services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      LDAP_ORGANISATION: "MyOrg"
      LDAP_DOMAIN: "myorg.com"
      LDAP_ADMIN_PASSWORD: admin
    ports:
      - "389:389"
    volumes:
      - ./ldap-data:/var/lib/ldap
      - ./ldap-config:/etc/ldap/slapd.d